[[redirects]]
from = "/api/*"
to = "http://nodeposts-env.eba-bqp3uqyx.us-east-2.elasticbeanstalk.com/api/:splat"
status = 200
force = true

[[redirects]]
from = "/api/posts/*"
to = "http://nodeposts-env.eba-bqp3uqyx.us-east-2.elasticbeanstalk.com/api/posts/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

